"Tum Hi Ho",
"Ae Dil Hai Mushkil",
"Bekhayali",
"Galliyan",
"Bin Tere",
"Pehla Nasha",
"Main Phir Bhi Tumko Chahunga",
"Tum Se Hi",
"Ae Mere Humsafar",
"Tujhe Dekha To",
"Dil Diyan Gallan",
"Kaabil Hoon",
"Teri Meri",
"Jen Len De",
"Pe Loon",
"Baarish",
"Jeene Laga Hoon",
"Dl To Bachcha Hai Ji",
"Tere Mast Mast Do Nain",
"Fakira",
"Tere Naina",
"Kaun Tujhe",
"Hua Hain Aaj Pehli Baar",
"Piya O Re Piya",
"Tumse Hi Tumse",
"Jag Ghoomeya",
"Mora Piya",
"Wajah Tum Ho",
"Banjaara",
"Tu Meri",
"Nazm Nazm",
"Dil Meri Na Sune",
"Paniyon Sa",
"Char Kadam",
"Tere Sang Yaara",
"Suraj Dooba Hai",
"Be Inthehaan",
"Agar Tum Saath Ho",
"Sunn Raha Hai",
"Tera Deedar Hua",
"Ek Ladki Ko Dekha",
"Baatein Kuch Ankahein Si",
"Ishq Wala Love",
"Dil Ko",
"Tum Hi Aana",
"Mera Mann",
"Woh Lamhe Who Baatein",
"Saibo",
"Oh Saathi",
"Main Duniya Bhula Doonga",
"Tera Yaar Hoon Mein",
"Chal Ghar Chale",
"Tu Hi Meri Shab Hai",
"Pal",
"Soch Na Sake",
"Yeh Dooriyan",
"Ishq Bina",
"Kabhi Alvida Naa Kehna",
"Call Me Dil",
"Sanam Re",
"Akele Hain To Kya Gum Hai",
"Humko Humise Churalo",
"Chand Chupa Badal Mein",
"Dil Deewana",
"Mein Tenu Samjhawan Ki",
"Bahut Pyar Karte Hain",
"Aankhon Mein Aansoon",
"Dheere Dheere Se Meri Zindagi Mein Aa Na",
"Na Tum Jaano Na Hum",
"Tujhe Kitna Chahne Lage",
"Gazab Ka Hai Din",
"Tera Hone Laga Hoon",
"Kuch Na Kaho",
"Zehnaseeb",
"Mere Rang Mein Rangane Wali",
"Pehli Nazar Mein",
"Nazar Ke Samne",
"Mitwa",
"Woh Pehli Bar Jab Hum Mile",
"Maula Mere Maula",
"Tadap Tadap Ke",
"Tujhko Jo Paya",
"Dil Kya Kare",
"Main Shair To Nahin",
"Yeh Jo Mohabbat Hai",
"Pal Pal Dil Ke Paas",
"Dilber Mere Kab Tak Mujhe",
"Tere Dar Pe Sanam Chale Aaye",
"Saagar Kinare",
"Chhookar Mere Man Ko Kiya Toone Kya Ishaara",
"Dhak Dhak Karne Laga",
"Neele Neele Ambar Par",
"Zara Sa",
"Gulabi Ankhen Jo Teri",
"Tujh Me Rab Dikhta Hai",
"Oh Meri Jaan",
"Tu Meri Zindagi Hai",
"Kya Mujhe Pyar Hai",
"Jiya Dhadak Dhadak",
"Tera Fitoor",
"Hum Tum",
"Tere Bina",
"Agar Tum Mil Jao",
"Do Dil Mil Rahe Hain",
"Hum Bane Tum Bane",
"Salaam-E-Ishq",
"My Dil Goes Hmmm",
"Rishte Naate",
"Chhupana Bhi Nahin Aata",
"Jab Hum Jawan Honge",
"Tum Dil Ki Dhadkan Mein",
"Hawaayein",
"Mein Koi Aisa Geet Gaoon",
"Ab Tere Bin",
"Tu Mohabbat Hai",
"Chana Mereya",
"Aanewala Pal",
"Kya Khoob Lagti Ho",
"Bakhuda Tumhi Ho",
"Wajah Tum Ho",
"Kuch Toh Hai",
"Sach Keh Raha Hai",
"Aankhon Ki Gustakhiyaan",
"Humsafar",
"Jaane Do Na",
"Ek Pyar Ka Naghma Hai",
"Tum Ho",
"Chand Sifarish",
"Enna Sona",
"Tum Tak",
"Lae Dooba",
"Wada Kar Le Sajna",
"Yeh Shaam Mastani",
"Oh Ho Jaane Jaana",
"Dil Hai Ke Manta Nahin",
"Tere Naam",
"Jaane Kaise Kab Kahan",
"You and Me",
"Tum Mere Ho",
"Kinna Sona",
"Roz Roz Aankhon Tale",
"Kabootar Ja Ja Ja",
"Bairiyaa",
"Aate Jaate Haste Gaate",
"Dekho Rootha Na Karo",
"Chehra Hai Ya Chand Khila Hai",
"Jab Se Tere Naina",
"Oh Mere Dil Ke Chain",
"Mujhe Neend Na Aaye",
"Ankhiyon Ke Jharokhon Se",
"Kate Nahin Kat Te",
"Bolna",
"Achha To Hum Chalte Hain",
"Muskurane",
"Rimjhim Gire Sawan",
"Tu Mera Hero Hain",
"Aaj Rapat Jaayen To",
"Kabhi Kabhi Mere Dil Mein",
"Baghon Mein Bahar Hai",
"Humein Tumese Pyaar Kitna",
"Tum Se",
"Dekha Hai Pehli Baar",
"Chura Liya Hai Tumne Jo Dil Ko",
"Suraj Hua Maddham",
"Tumhein Apna Banane Ki",
"Shayad Meri Shaadi Ka Khayal",
"Waada Raha Sanam",
"Tu Rootha To Main Ro Doongi",
"Sun Saathiya",
"Tumsa Nahin Dekha",
"Mera Dil Bhi Kitna Pagal Hai",
"Teri Umeed Tera Intezar",
"Bahara",
"Tum Aa Gaye Ho Noor Aa Gaya",
"Ae Mere Humsafar",
"Tumse Milke",
"Bheegay Hont",
"Kya Dekhte Ho Surat Tumhari",
"Hothon Se Chholon Tum",
"Khuda Jaane",
"Tere Bin",
"Jaane Kyun",
"Agar Tum Na Hote",
"Khamoshiyan",
"Angrezi Men Kahate Hain Ke I Love You",
"Tumko Dekha To Yeh Khayal",
"Koi Yeh Kaise Bataye",
"Tere Liye",
"Ye Ladki Zarasi Deewani Lagati Hai",
"Aaja Aaja Main Hoon Pyar Tera",
"Ek Dil Ek Jaan",
"Tere Bina Zindagi Se",
"Wada Karo Nahin Chodoge Tum Mera Saath",
"Jaane De Jaane De Mujhe",
"Sau Aasmaan",
"Kahin Door Jab Din Dhal Jaaye",
"Mere Samne Wali Khidki Mein",
"Jadoo Hai Tera",
"Love You Zindagi",
"Pyaar Manga Hai Tumhi Se",
"Do Lafzon Ki Hai Dil Ki Kahani",
"Mast Magan",
"Chura Ke Dil Mera",
"Gerua",
"Aaja Shaam Hone Aayee",
"Pashmina",
"Roop Tera Mastana",
"Mere Dil Mein Aaj Kya Hai",
"Zara Zara",
"Ude Dil Befikre",
"Ae Dil Hai Mushkil Jeena Yaha",
"Kaisa Lagta Hai",
"Ae Kash Ke Hum",
"Koi Fariyaad",
"Geet Gaata Hoon Main",
"Roke Na Ruke Naina",
"Ek Ladki Bheegi Bhaagi Si",
"Tera Naam Liya",
"Lo Safar",
"Pukarta Chala Hun Mein",
"Mujhko Barsaat Bana Lo",
"Hanste Hanste",
"Teri Yaad Aa Rahi Hai",
"Dil Mera Churaya Kyun",
"Humdard",
"Mere Naina Sawan Bhadon",
"Bheegi Bheegi Raaton Mein",
"Saathiya",
"Mere Jeevan Saathi",
"Tu Pyar Hai Kisi Aur Ka",
"Bahon Ke Darmiyan",
"In Dino",
"Ik Vaari Aa",
"Thodi Der",
"Khwabon Ke Parindey",
"Toota Jo Kabhi Tara",
"Naina",
"Maine Tujhko Dekha",
"Halka Halka",
"Yeh Tera Ghar Yeh Mera Ghar",
"Samundar Mein Nahake",
"Tum Jo Mil Gaye Ho",
"Qaafirana",
"Janam Janam",
"Pehli Baar",
"Dil Jo Na Keh Saka",
"Yeh Fitoor Mera",
"Zindagi Ka Safar",
"Lambi Si Judaiyaan",
"Meherbaan",
"Dil Mera",
"Tu Hi Yaar Mera",
"Ek Ajanabee Haseena Se",
"Jeena Hai Pyar Mein Jeena",
"Saathi Re",
"Baharon Phool Barsao",
"Keh Do Ki Tum Ho Meri",
"Ajj Din Chadheya",
"Gehra Ishq",
"Sun Sahiba Sun",
"Teher Ja",
"Ji Huzoori",
"Gata Rahe Mera Dil",
"Mana Ki Hum Yaar Nahin",
"Tu Hi Re",
"Chaudhvin Ka Chand Ho",
"Yeh Kahan Aa Gaye Hum",
"Tumhe Jo Maine Dekha",
"Ishq Bulaava",
"Tera Hua",
"Stay A Little Longer",
"Ve Maahi",
"Abhi Na Jao Chod Kar",
"Ishq Di Baajiyaan",
"Yeh Ishq Hain",
"Gun Guna Rahe Hai Bhanvare",
"Bade Achhe Lagte Hain",
"Zaalima",
"Dil Ne Yeh Kaha Hai Dil Se",
"Jo Haal Dil Ka",
"Pukarta Chala Hoon Mein",
"Aaya Mausam Dosti Ka",
"Tu Hai Ki Nahi",
"Chingari Koi Bhadke",
"Hum Bewafa Hargiz Na The",
"Yeh Raaten Yeh Mausam",
"Rim Jhim Rim Jhim",
"Dil Kyun Yeh Mera",
"Koi Mil Gaya",
"Dhoonde Akhiyaan",
"Saathiya Toone Kya Kiya",
"Dil Ka Alam",
"Yeh Dil Na Hota Bechara",
"Thodi Jagah",
"Zara Zara Touch Me",
"Mere Naam Tu",
"Tu Chahiye",
"Do Deewane Shaher Mein",
"Likhe Jo Khat Tujhe",
"Dil Pukare Aa Re",
